### ISSUE TITLE
Permission denied errors from backup script

### ISSUE THREAD

**Issue by djowett** [MaximeThoonsen/ansible-autopostgresqlbackup#5]
Each morning I get an message with these errors

    Subject: 	ERRORS REPORTED: PostgreSQL Backup error Log for <Servername> - 2016-08-31_08h39m
    ...

    could not change directory to "/root": Permission denied
    could not change directory to "/root": Permission denied
    could not change directory to "/root": Permission denied
    could not change directory to "/root": Permission denied
    could not change directory to "/root": Permission denied

This is on Ubuntu 14.04.3 (trusty)

**Comment by MaximeThoonsen** [comment]
@djowett which version of ansible do you use ? Maybe we have to change the "sudo: yes" by "become: yes" to be compatible with the newest Ansible version

**Comment by djowett** [comment]
@MaximeThoonsen thanks for the merge.  I am using Ansible 2.1.1.0 - I had thought about the sudo -> become thing, did you have thoughts about how to support Ansible 2.x and 1.x?
(it wasn't the issue here)

**Comment by MaximeThoonsen** [comment]
@djowett no but I think we can use become now

**Comment by MaximeThoonsen** [comment]
and drop the support for the earliest version of Ansible

**Comment by djowett** [comment]
That's good with me!

**Comment by djowett** [comment]
Actually, my fix isn't correct.  The problem seems more related to the `su` in the `/usr/sbin/autopostgresqlbackup` script.  It seems that it should be `su -` to correctly pick up the postgres environment.

HOWEVER, I'm inclined to add the cronjob to the postgres user then the su wouldn't be necessary.

**Comment by djowett** [comment]
@MaximeThoonsen I'd be interested in what you think on the [branch](https://github.com/jowent/ansible-autopostgresqlbackup/tree/execute-as-postgres-user) I just pushed.  I don't think it should be merged as is, but good for discussion.   As I say in the commit:

1. it won't suit everybody
2. Anyone using prior versions of the role will want to delete the root cronjob (we could do this through ansible of course!)
